# Form implementation generated from reading ui file 'd:\STEI\Jurusan\Semester-4\RPL\Tubes\New folder\IF2250-2023-K01-G09-yanyard\ui_temp\detailtaneman\detailtanaman.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(996, 770)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}\n"
"#scrollArea {\n"
"    background-color: #F7F4D9;\n"
"}\n"
"#header {\n"
"    background-color: #3C6255;\n"
"}\n"
"#image {\n"
"    border-radius: 62px;\n"
"}\n"
"\n"
"#main {\n"
"    background-color: #F7F4D9;\n"
"}\n"
"\n"
"#footer {\n"
"    background-color: #F7F4D9;\n"
"}\n"
"\n"
"#btn_back {\n"
"    color: #F7F4D9;\n"
"    font-size: 20px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#btn_back:hover {\n"
"    color: #DEDBC0;\n"
"}\n"
"\n"
"\n"
"#tdl_back:hover {\n"
"    color: #DEDBC0;\n"
"}\n"
"#btn_prev, #btn_next {\n"
"    background-color: #61876E;\n"
"    border-radius: 25px;\n"
"}\n"
"\n"
"#btn_prev:hover {\n"
"    background-color: #486E55;\n"
"}\n"
"\n"
"#btn_next:hover {\n"
"    background-color: #486E55;\n"
"}\n"
"\n"
"#namatanaman {\n"
"    color: #3C6255;\n"
"    padding: 15px 70px;\n"
"    font-size: 24px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#box_description_artikel {\n"
"    color: #F9F9F9;\n"
"    background-color: #3C6255;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"\n"
"#text_description_artikel {\n"
"    color: #F9F9F9;\n"
"    padding: 10px 8px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"#deskripsi {\n"
"    color: #000000;\n"
"    padding: 10px 8px;\n"
"    font-size: 11px;\n"
"}\n"
"\n"
"#addtdl{\n"
"    color: #F7F4D9;\n"
"    background-color: #61876E;\n"
"    padding: 5px 20px;\n"
"    border-radius: 15px;\n"
"    font-size: 10px;\n"
"}\n"
"#listtodo{\n"
"    color: #F7F4D9;\n"
"    background-color: #61876E;\n"
"    padding: 6px 20px;\n"
"    border-radius: 15px;\n"
"    font-size: 11px;\n"
"}\n"
"\n"
"#listjam{\n"
"    color: #F7F4D9;\n"
"    background-color: #61876E;\n"
"    padding: 6px 30px;\n"
"    border-radius: 15px;\n"
"    font-size: 11px;\n"
"}\n"
"\n"
"#addjurnal{\n"
"    color: #F7F4D9;\n"
"    background-color: #61876E;\n"
"    padding: 5px 20px;\n"
"    border-radius: 15px;\n"
"    font-size: 10px;\n"
"}\n"
"\n"
"#jam{\n"
"    color: #F7F4D9;\n"
"    background-color: #61876E;\n"
"    padding: 5px 20px;\n"
"    border-radius: 15px;\n"
"    font-size: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 972, 746))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.header_2 = QtWidgets.QWidget(parent=self.header)
        self.header_2.setMinimumSize(QtCore.QSize(0, 60))
        self.header_2.setObjectName("header_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_temp = QtWidgets.QFrame(parent=self.header_2)
        self.frame_temp.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_temp.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_temp.setObjectName("frame_temp")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_temp)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_back = QtWidgets.QPushButton(parent=self.frame_temp)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/left__arrow2.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_back.setIcon(icon)
        self.btn_back.setIconSize(QtCore.QSize(24, 24))
        self.btn_back.setAutoExclusive(False)
        self.btn_back.setFlat(False)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_3.addWidget(self.btn_back, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout_2.addWidget(self.frame_temp)
        self.frame_logo = QtWidgets.QFrame(parent=self.header_2)
        self.frame_logo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_logo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_logo.setObjectName("frame_logo")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_logo)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.logo = QtWidgets.QLabel(parent=self.frame_logo)
        self.logo.setMinimumSize(QtCore.QSize(0, 0))
        self.logo.setMaximumSize(QtCore.QSize(42, 42))
        self.logo.setPixmap(QtGui.QPixmap("d:\\STEI\\Jurusan\\Semester-4\\RPL\\Tubes\\New folder\\IF2250-2023-K01-G09-yanyard\\ui_temp\\detailtaneman\\../artikel/logo_circle.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.horizontalLayout_5.addWidget(self.logo)
        self.horizontalLayout_2.addWidget(self.frame_logo)
        self.frame_temp_2 = QtWidgets.QFrame(parent=self.header_2)
        self.frame_temp_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_temp_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_temp_2.setObjectName("frame_temp_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_temp_2)
        self.label_2.setGeometry(QtCore.QRect(220, 20, 58, 16))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.frame_temp_2)
        self.horizontalLayout_4.addWidget(self.header_2)
        self.verticalLayout.addWidget(self.header)
        self.title = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.title.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.title.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title.setObjectName("title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.title)
        self.verticalLayout_2.setContentsMargins(0, 12, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.image = QtWidgets.QLabel(parent=self.title)
        self.image.setMinimumSize(QtCore.QSize(0, 0))
        self.image.setMaximumSize(QtCore.QSize(150, 200))
        self.image.setMidLineWidth(-54)
        self.image.setPixmap(QtGui.QPixmap("d:\\STEI\\Jurusan\\Semester-4\\RPL\\Tubes\\New folder\\IF2250-2023-K01-G09-yanyard\\ui_temp\\detailtaneman\\../../../../Downloads/stroberi.jpeg"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.verticalLayout_2.addWidget(self.image, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.namatanaman = QtWidgets.QLabel(parent=self.title)
        self.namatanaman.setMaximumSize(QtCore.QSize(300, 50))
        self.namatanaman.setObjectName("namatanaman")
        self.verticalLayout_2.addWidget(self.namatanaman, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.addWidget(self.title)
        self.frame_6 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMaximumSize(QtCore.QSize(900, 500))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.deskripsi = QtWidgets.QPlainTextEdit(parent=self.frame_6)
        self.deskripsi.setGeometry(QtCore.QRect(23, 0, 901, 71))
        self.deskripsi.setReadOnly(True)
        self.deskripsi.setObjectName("deskripsi")
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 961, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_5 = QtWidgets.QFrame(parent=self.layoutWidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label = QtWidgets.QLabel(parent=self.frame_5)
        self.label.setGeometry(QtCore.QRect(20, 10, 161, 41))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("d:\\STEI\\Jurusan\\Semester-4\\RPL\\Tubes\\New folder\\IF2250-2023-K01-G09-yanyard\\ui_temp\\detailtaneman\\../../../../Downloads/To Do List (3).png"))
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.frame_5)
        self.frame = QtWidgets.QFrame(parent=self.layoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.addtdl = QtWidgets.QPushButton(parent=self.frame)
        self.addtdl.setGeometry(QtCore.QRect(300, 20, 141, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addtdl.sizePolicy().hasHeightForWidth())
        self.addtdl.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\STEI\\Jurusan\\Semester-4\\RPL\\Tubes\\New folder\\IF2250-2023-K01-G09-yanyard\\ui_temp\\detailtaneman\\../../../../Downloads/add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addtdl.setIcon(icon1)
        self.addtdl.setIconSize(QtCore.QSize(13, 13))
        self.addtdl.setObjectName("addtdl")
        self.horizontalLayout_7.addWidget(self.frame)
        self.verticalLayout.addWidget(self.frame_2)
        self.list_tdl = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.list_tdl.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.list_tdl.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.list_tdl.setObjectName("list_tdl")
        self.listjam = QtWidgets.QListWidget(parent=self.list_tdl)
        self.listjam.setGeometry(QtCore.QRect(20, 10, 151, 41))
        self.listjam.setObjectName("listjam")
        item = QtWidgets.QListWidgetItem()
        self.listjam.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listjam.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listjam.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listjam.addItem(item)
        self.listtodo = QtWidgets.QListWidget(parent=self.list_tdl)
        self.listtodo.setGeometry(QtCore.QRect(195, 10, 731, 41))
        self.listtodo.setObjectName("listtodo")
        item = QtWidgets.QListWidgetItem()
        self.listtodo.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listtodo.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listtodo.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listtodo.addItem(item)
        self.verticalLayout.addWidget(self.list_tdl)
        self.frame_7 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.frame_7)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 961, 61))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_8 = QtWidgets.QFrame(parent=self.layoutWidget1)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 161, 41))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("d:\\STEI\\Jurusan\\Semester-4\\RPL\\Tubes\\New folder\\IF2250-2023-K01-G09-yanyard\\ui_temp\\detailtaneman\\../../../../Downloads/To Do List (3).png"))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(parent=self.layoutWidget1)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.addjurnal = QtWidgets.QPushButton(parent=self.frame_9)
        self.addjurnal.setGeometry(QtCore.QRect(300, 20, 141, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addjurnal.sizePolicy().hasHeightForWidth())
        self.addjurnal.setSizePolicy(sizePolicy)
        self.addjurnal.setIcon(icon1)
        self.addjurnal.setIconSize(QtCore.QSize(13, 13))
        self.addjurnal.setObjectName("addjurnal")
        self.horizontalLayout_8.addWidget(self.frame_9)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_4 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout.addWidget(self.frame_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_back.setText(_translate("MainWindow", " Kembali"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.namatanaman.setText(_translate("MainWindow", "Stroberi"))
        self.deskripsi.setPlainText(_translate("MainWindow", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin at nibh volutpat, eleifend augue vel, hendrerit augue. Fusce egestas ipsum dolor, id convallis nulla cursus eleifend. Aliquam erat volutpat. Suspendisse facilisis quis ex non vestibulum. In ultricies porta dapibus. Praesent in arcu vel risus auctor elementum id at ex. Vestibulum gravida, odio ac dapibus convallis, erat lacus molestie turpis, in tristique urna mauris vitae ligula. "))
        self.addtdl.setText(_translate("MainWindow", "ADD TO DO LIST"))
        __sortingEnabled = self.listjam.isSortingEnabled()
        self.listjam.setSortingEnabled(False)
        item = self.listjam.item(0)
        item.setText(_translate("MainWindow", "07.00"))
        item = self.listjam.item(1)
        item.setText(_translate("MainWindow", "09.30"))
        item = self.listjam.item(2)
        item.setText(_translate("MainWindow", "14.00"))
        item = self.listjam.item(3)
        item.setText(_translate("MainWindow", "19.00"))
        self.listjam.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listtodo.isSortingEnabled()
        self.listtodo.setSortingEnabled(False)
        item = self.listtodo.item(0)
        item.setText(_translate("MainWindow", "siram stroberi"))
        item = self.listtodo.item(1)
        item.setText(_translate("MainWindow", "nyamnyam"))
        item = self.listtodo.item(2)
        item.setText(_translate("MainWindow", "nomnom"))
        item = self.listtodo.item(3)
        item.setText(_translate("MainWindow", "kasih pupuk"))
        self.listtodo.setSortingEnabled(__sortingEnabled)
        self.addjurnal.setText(_translate("MainWindow", "ADD JURNAL"))
