# Form implementation generated from reading ui file 'd:\STEI\Jurusan\Semester-4\RPL\Tubes\New folder\IF2250-2023-K01-G09-yanyard\ui_temp\datatanaman\datatanaman2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 600)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(parent=self.centralwidget)
        self.header.setMinimumSize(QtCore.QSize(0, 60))
        self.header.setStyleSheet("#header {\n"
"    background-color: #3C6255;\n"
"}")
        self.header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_temp = QtWidgets.QFrame(parent=self.header)
        self.frame_temp.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_temp.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_temp.setObjectName("frame_temp")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_temp)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_back = QtWidgets.QPushButton(parent=self.frame_temp)
        self.btn_back.setStyleSheet("#btn_back {\n"
"    color: #F7F4D9;\n"
"    font-size: 20px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#btn_back:hover {\n"
"    color: #DEDBC0;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/left__arrow2.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_back.setIcon(icon)
        self.btn_back.setIconSize(QtCore.QSize(24, 24))
        self.btn_back.setAutoExclusive(False)
        self.btn_back.setFlat(False)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_3.addWidget(self.btn_back, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout.addWidget(self.frame_temp)
        self.frame_logo = QtWidgets.QFrame(parent=self.header)
        self.frame_logo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_logo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_logo.setObjectName("frame_logo")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_logo)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo = QtWidgets.QLabel(parent=self.frame_logo)
        self.logo.setMinimumSize(QtCore.QSize(0, 0))
        self.logo.setMaximumSize(QtCore.QSize(42, 42))
        self.logo.setPixmap(QtGui.QPixmap("d:\\STEI\\Jurusan\\Semester-4\\RPL\\Tubes\\New folder\\IF2250-2023-K01-G09-yanyard\\ui_temp\\datatanaman\\../artikel/logo_circle.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.horizontalLayout_2.addWidget(self.logo)
        self.horizontalLayout.addWidget(self.frame_logo)
        self.frame_temp_2 = QtWidgets.QFrame(parent=self.header)
        self.frame_temp_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_temp_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_temp_2.setObjectName("frame_temp_2")
        self.horizontalLayout.addWidget(self.frame_temp_2)
        self.verticalLayout.addWidget(self.header)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setStyleSheet("#scrollArea {\n"
"    background-color: #F7F4D9;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    width: 20px;\n"
"    margin: 5px;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #3C6255;\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: #23493C;\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 960, 540))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setStyleSheet("#main {\n"
"    background-color: #F7F4D9;\n"
"}")
        self.main.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main.setObjectName("main")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_3.setContentsMargins(18, -1, 18, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_title = QtWidgets.QFrame(parent=self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_title.sizePolicy().hasHeightForWidth())
        self.frame_title.setSizePolicy(sizePolicy)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 9)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_title_tdl = QtWidgets.QLabel(parent=self.frame_title)
        self.label_title_tdl.setMinimumSize(QtCore.QSize(278, 68))
        self.label_title_tdl.setStyleSheet("#label_title_tdl {\n"
"    color: #F7F4D9;\n"
"    background-color: #3C6255;\n"
"    border-radius: 25px;\n"
"    font-size: 28px;\n"
"    font-weight: 600;\n"
"}")
        self.label_title_tdl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title_tdl.setObjectName("label_title_tdl")
        self.horizontalLayout_5.addWidget(self.label_title_tdl, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_3.addWidget(self.frame_title)
        self.frame_data_tanaman = QtWidgets.QFrame(parent=self.main)
        self.frame_data_tanaman.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_data_tanaman.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_data_tanaman.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_data_tanaman.setObjectName("frame_data_tanaman")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_data_tanaman)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.grid_layout_tanaman = QtWidgets.QGridLayout()
        self.grid_layout_tanaman.setHorizontalSpacing(36)
        self.grid_layout_tanaman.setVerticalSpacing(72)
        self.grid_layout_tanaman.setObjectName("grid_layout_tanaman")
        self.frame_tanaman_1 = QtWidgets.QFrame(parent=self.frame_data_tanaman)
        self.frame_tanaman_1.setMinimumSize(QtCore.QSize(0, 220))
        self.frame_tanaman_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_tanaman_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_tanaman_1.setObjectName("frame_tanaman_1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_tanaman_1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_nama = QtWidgets.QFrame(parent=self.frame_tanaman_1)
        self.frame_nama.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_nama.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_nama.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_nama.setObjectName("frame_nama")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_nama)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_name = QtWidgets.QLabel(parent=self.frame_nama)
        self.label_name.setStyleSheet("#label_name {\n"
"    color: #3C6255;\n"
"    font-size: 20px;\n"
"    font-weight: 800;\n"
"}")
        self.label_name.setObjectName("label_name")
        self.horizontalLayout_4.addWidget(self.label_name, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_4.addWidget(self.frame_nama)
        self.frame_img = QtWidgets.QFrame(parent=self.frame_tanaman_1)
        self.frame_img.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_img.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_img.setObjectName("frame_img")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_img)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_img = QtWidgets.QWidget(parent=self.frame_img)
        self.widget_img.setMinimumSize(QtCore.QSize(123, 150))
        self.widget_img.setStyleSheet("#widget_img {\n"
"    border-radius:30px;\n"
"    background-color: #3C6255;\n"
"}")
        self.widget_img.setObjectName("widget_img")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_img)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_8.addWidget(self.widget_img, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_4.addWidget(self.frame_img)
        self.frame_date = QtWidgets.QFrame(parent=self.frame_tanaman_1)
        self.frame_date.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_date.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_date.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_date.setObjectName("frame_date")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_date)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_date = QtWidgets.QLabel(parent=self.frame_date)
        self.label_date.setStyleSheet("#label_date {\n"
"    color: #61876E;\n"
"    font-size: 11px;\n"
"    font-weight: 600;\n"
"}")
        self.label_date.setObjectName("label_date")
        self.verticalLayout_6.addWidget(self.label_date, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_4.addWidget(self.frame_date)
        self.grid_layout_tanaman.addWidget(self.frame_tanaman_1, 0, 0, 1, 1)
        self.frame_tanaman_3 = QtWidgets.QFrame(parent=self.frame_data_tanaman)
        self.frame_tanaman_3.setMinimumSize(QtCore.QSize(0, 220))
        self.frame_tanaman_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_tanaman_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_tanaman_3.setObjectName("frame_tanaman_3")
        self.grid_layout_tanaman.addWidget(self.frame_tanaman_3, 0, 2, 1, 1)
        self.frame_tanaman_2 = QtWidgets.QFrame(parent=self.frame_data_tanaman)
        self.frame_tanaman_2.setMinimumSize(QtCore.QSize(0, 220))
        self.frame_tanaman_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_tanaman_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_tanaman_2.setObjectName("frame_tanaman_2")
        self.grid_layout_tanaman.addWidget(self.frame_tanaman_2, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.grid_layout_tanaman)
        self.verticalLayout_3.addWidget(self.frame_data_tanaman)
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.main)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_back.setText(_translate("MainWindow", " Kembali"))
        self.label_title_tdl.setText(_translate("MainWindow", "Data Tanaman"))
        self.label_name.setText(_translate("MainWindow", "Strobeyi"))
        self.label_date.setText(_translate("MainWindow", "since March 2023"))
